CREATE DATABASE BARBEARIA;

CREATE TABLE BARBEIRO (
   IDBARBEIRO SERIAL PRIMARY KEY,
   NOMECOMPLETOBARBEIRO VARCHAR(30), 
   INSTAGRAM VARCHAR(30),
   TELEFONE VARCHAR(15)
);

CREATE TABLE CLIENTE (
   IDCLIENTE SERIAL PRIMARY KEY,
   NOMECOMPLETOCLIENTE VARCHAR(30),
   SENHA INT NOT NULL,
   EMAIL VARCHAR(40),  
   TELEFONE VARCHAR(15),
   CPF VARCHAR(15)
);

CREATE TABLE PRODUTO (
   IDPRODUTO SERIAL PRIMARY KEY,
   NOMEPRODUTO VARCHAR(50),
   PRECO NUMERIC(10,2),
   QUANTIDADE INT,
   TIPO VARCHAR(50),
   VALIDADE DATE,
   DESCRICAO TEXT
);

CREATE TABLE VENDA (
   IDVENDA SERIAL PRIMARY KEY,
   PRECO NUMERIC(10,2),
   DATAVENDA DATE,
   FORMAPAG VARCHAR(20)
);

CREATE TABLE VENDACLIENTE (
   IDVENDA INTEGER,
   IDCLIENTE INTEGER,
   PRIMARY KEY (IDVENDA, IDCLIENTE),
   FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA),
   FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE)
);

CREATE TABLE VENDAMERCADORIA (
   IDPRODUTO INTEGER,
   IDVENDA INTEGER,
   PRIMARY KEY (IDPRODUTO, IDVENDA),
   FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO),
   FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA)
);

CREATE TABLE AGENDAMENTO(
   IDAGENDAMENTO SERIAL PRIMARY KEY,
   IDCLIENTE INTEGER,
   IDBARBEIRO INTEGER,
   IDVENDA INTEGER,
   HORA TIME,
   DATA DATE,
   STATUS VARCHAR(10),
   NOTA INT,
   DESCRICAO TEXT,
   FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
   FOREIGN KEY (IDBARBEIRO) REFERENCES BARBEIRO(IDBARBEIRO),
   FOREIGN KEY (IDVENDA) REFERENCES VENDA(IDVENDA)
);

CREATE TABLE AGENDAMENTOSERVICO(
   IDAGENDAMENTO INTEGER,
   IDPRODUTO INTEGER,
   PRIMARY KEY (IDAGENDAMENTO, IDPRODUTO),
   FOREIGN KEY (IDAGENDAMENTO) REFERENCES AGENDAMENTO(IDAGENDAMENTO),
   FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

CREATE TABLE CATEGORIA (
   IDPRODUTO INTEGER,
   NOMECATEGORIA VARCHAR(30),
   FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

CREATE TABLE CUPOM (
   IDCUPOM SERIAL PRIMARY KEY,
   DESCRICAO TEXT,
   DESCONTO NUMERIC(5,2),
   DATAINICIO DATE,
   DATATERMINO DATE
);

CREATE TABLE DESCONTO (
   IDCUPOM INTEGER,
   IDPRODUTO INTEGER,
   PRIMARY KEY (IDCUPOM, IDPRODUTO),
   FOREIGN KEY (IDCUPOM) REFERENCES CUPOM(IDCUPOM),
   FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);

CREATE TABLE REALIZA (
   IDBARBEIRO INTEGER,
   IDPRODUTO INTEGER,
   PRIMARY KEY (IDBARBEIRO, IDPRODUTO),
   FOREIGN KEY (IDBARBEIRO) REFERENCES BARBEIRO(IDBARBEIRO),
   FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO(IDPRODUTO)
);
